###############################
########## NameSpace ##########
###############################
apiVersion: v1
kind: Namespace
metadata:
  name: ml-app
---

########################################
########## Model Training Pod ##########
########################################
apiVersion: v1
kind: Pod
metadata:
  name: model-training-pod
  namespace: ml-app
spec:
  containers:
  - name: data-processing
    image: jurnjie/data-processing:latest
    volumeMounts:
    - mountPath: "/app/data_309"
      name: processed-data-volume

  - name: model-training
    image: 200iqkid/model-training:latest
    volumeMounts:
    - mountPath: "/app/data_309"  
      name: processed-data-volume
    - mountPath: '/mnt/saved_model' 
      name: saved-model-volume

  volumes:
  - name: processed-data-volume
    persistentVolumeClaim:
      claimName: processed-data-pvc
  - name: saved-model-volume
    persistentVolumeClaim:
      claimName: saved-model-pvc
---

#######################################
########## Persistent Volume ##########
#######################################

# PV for processed data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: processed-data-pv  # Name of the Persistent Volume for processed data
  namespace: ml-app
spec:
  capacity:
    storage: 4Gi  
  accessModes:
    - ReadWriteMany  
  hostPath:
    path: "/mnt/processed_data"  # Path on the host machine where the processed data is stored
  persistentVolumeReclaimPolicy: Retain
---

# PV for saved model
apiVersion: v1
kind: PersistentVolume
metadata:
  name: saved-model-pv  # Name of the Persistent Volume for the saved model
  namespace: ml-app
spec:
  capacity:
    storage: 4Gi  
  accessModes:
    - ReadWriteMany  
  hostPath:
    path: "/mnt/saved_model"  # Path on the host machine where the model will be saved
  persistentVolumeReclaimPolicy: Retain
---

#############################################
########## Persistent Volume Claim ##########
#############################################

# PVC for processed data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: processed-data-pvc  # Name of the PVC that will request the processed data volume
  namespace: ml-app  
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 4Gi
---

# PVC for saved model
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saved-model-pvc  # Name of the PVC that will request the saved model volume
  namespace: ml-app  
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 4Gi  



