# Define namespace
apiVersion: v1
kind: Namespace
metadata:
  name: ml-app
---
apiVersion: v1
kind: Pod
metadata:
  name: model-training-pod
  namespace: ml-app
spec:
  containers:
  - name: data-processing-container
    image: jurnjie/data-processing:latest
    volumeMounts:
    - mountPath: "/app/data_309"
      name: processed-data-volume
  - name: model-training-container
    image: 200iqkid/model-training:latest
    volumeMounts:
    - mountPath: "/app/data_309"  # Path inside the container for the processed data
      name: processed-data-volume
    - mountPath: '/mnt/saved_model' # Path inside the container where the model will be saved
      name: saved-model-volume
  volumes:
  - name: processed-data-volume
    persistentVolumeClaim:
      claimName: processed-data-pvc
  - name: saved-model-volume
    persistentVolumeClaim:
      claimName: saved-model-pvc



