apiVersion: v1
kind: PersistentVolume
metadata:
  name: processed-data-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/app/data_309"  # This path should correspond to the location where jurnjie writes data
