apiVersion: v1
kind: Pod
metadata:
  name: model-writer-pod
spec:
  containers:
    - name: model-writer-container
      image: edysontan/train:latest
      volumeMounts:
        - mountPath: /mnt/data  # Path inside the container
          name: my-data-volume
  volumes:
    - name: my-data-volume
      persistentVolumeClaim:
        claimName: my-pvc  # Ensure this PVC exists and is correctly configured