apiVersion: v1
kind: PersistentVolume
metadata:
  name: store-model-vol
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt"  # Directory on the Kubernetes node