apiVersion: v1
kind: Pod
metadata:
  name: model-training-pod
spec:
  containers:
  - name: model-training-container
    image: yourdockerhubusername/model-trainer:latest
    command: ["python", "train.py"]
    volumeMounts:
    - mountPath: /mnt/data
      name: model-training-volume
    - mountPath: /mnt/model_training/saved_model
      name: model-output-volume
    env:
    - name: MODEL_SAVE_PATH
      value: "/mnt/model_training/saved_model/trained_model"
  volumes:
  - name: model-training-volume
    persistentVolumeClaim:
      claimName: model-training-pvc
  - name: model-output-volume
    persistentVolumeClaim:
      claimName: model-output-pvc