
# namespace for the cluster
apiVersion: v1
kind: Namespace
metadata:
  name: ml-app

---

# Service

apiVersion: v1
kind: Service
metadata:
  name: processing-service
  namespace: ml-app
spec:
  selector:
    app: data-processing
  ports:
  - protocol: TCP
    port: 84
    targetPort: 8084
  type: ClusterIP

---

# PV
# allow request of storage

apiVersion: v1
kind: PersistentVolume
metadata:
  name: processed-data-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---

# PVC 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: processed-data-pvc
  namespace: ml-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi

---

# Deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processing-deployment
  namespace: ml-app
  labels:
    app: data-processing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-processing
  template:
    metadata:
      labels:
        app: data-processing
    spec:
      containers:
      - name: data-processing-container
        image: 200iqkid/data-processing
        volumeMounts:
        - mountPath: "/app/processed_data"
          name: processed-data-pv
        env:
        - name: TRAIN_DIR
          value: "/app/data_309/train"
        - name: TEST_DIR
          value: "/app/data_309/test"
      # Connecting PVC to PV
      volumes:
      - name: processed-data-pv
        persistentVolumeClaim:
          claimName: processed-data-pvc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 10  # Keep a history of 10 revisions for rollback
  minReadySeconds: 5  # Minimum time a Pod should be ready before considered stable
  progressDeadlineSeconds: 600  # Deadline for progressing the deployment        
