apiVersion: v1
kind: PersistentVolume
metadata:
  name: dataprep-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"  # Directory on the Kubernetes node