apiVersion: v1
kind: Pod
metadata:
  name: retrieverpod
spec:
  containers:
    - name: python-container
      image: edysontan/inference
      volumeMounts:
        - mountPath: /mnt/data  # Path inside the container
          name: my-data-volume
  volumes:
    - name: my-data-volume
      persistentVolumeClaim:
        claimName: my-pvc