# Define the Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: ml-app

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-url
  namespace: ml-app
data:
  DP_POD_URL: "http://processing-service:84/start-processing"
  MOD_TRG_URL: "http://inference-pod/get-model-info" # change this
  RESULTS_URL: "http://inference-pod/get-model-info" # change this
  INF_POD_URL: "http://inference-service:83/predict"

---
# Flask App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: ml-app
spec:
  replicas: 3
  selector:
    matchLabels:
      chapter: flask
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        chapter: flask
    spec:
      containers:
      - name: flask-container
        image: edysontan/flask-app:latest
        env:
        - name: DP_POD_URL
          valueFrom:
            configMapKeyRef:
              name: flask-url
              key: DP_POD_URL
        - name: INF_POD_URL
          valueFrom:
            configMapKeyRef:
              name: flask-url
              key: INF_POD_URL
        - name: MOD_TRG_URL
          valueFrom:
            configMapKeyRef:
              name: flask-url
              key: MOD_TRG_URL
        - name: RESULTS_URL
          valueFrom:
            configMapKeyRef:
              name: flask-url
              key: RESULTS_URL
        ports:
        - containerPort: 5000 # set port 5000

---
# Flask app service
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: ml-app
  labels:
    chapter: flask
spec:
  type: NodePort  # LoadBalancer for external
  ports:
  - protocol: TCP
    port: 5000  # External port
    targetPort: 5000  # Flask app port inside the container
    nodePort: 30005
  selector:
    chapter: flask
